"""Initial migration: create all tables

Revision ID: c592e7ad4b2c
Revises: 
Create Date: 2025-11-07 11:25:45.646288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c592e7ad4b2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asx_code', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_asx_code'), 'companies', ['asx_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('asx_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('announcement_date', sa.DateTime(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('pdf_local_path', sa.Text(), nullable=True),
    sa.Column('markdown_path', sa.Text(), nullable=True),
    sa.Column('is_price_sensitive', sa.Boolean(), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_announcement_date'), 'announcements', ['announcement_date'], unique=False)
    op.create_index(op.f('ix_announcements_asx_code'), 'announcements', ['asx_code'], unique=False)
    op.create_index(op.f('ix_announcements_company_id'), 'announcements', ['company_id'], unique=False)
    op.create_index(op.f('ix_announcements_is_price_sensitive'), 'announcements', ['is_price_sensitive'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='unique_user_company_watchlist')
    )
    op.create_index(op.f('ix_watchlists_company_id'), 'watchlists', ['company_id'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_impact', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('llm_prompt_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_announcement_id'), 'analysis', ['announcement_id'], unique=True)
    op.create_index(op.f('ix_analysis_sentiment'), 'analysis', ['sentiment'], unique=False)
    op.create_table('stock_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('price_at_announcement', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_1h_after', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_1d_after', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('price_change_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('volume_at_announcement', sa.BigInteger(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('performance_1m_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('performance_3m_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('performance_6m_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_data_announcement_id'), 'stock_data', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_stock_data_company_id'), 'stock_data', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_data_company_id'), table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_announcement_id'), table_name='stock_data')
    op.drop_table('stock_data')
    op.drop_index(op.f('ix_analysis_sentiment'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_announcement_id'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_company_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_announcements_is_price_sensitive'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_company_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_asx_code'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_announcement_date'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_asx_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
